import { type ClassValue, clsx } from '@kobato/ui/lib/clsx'
import { extendTailwindMerge } from 'tailwind-merge'

// Project-wide `cn` helper — custom `tailwind-merge` that registers every `@theme`
// token so custom utilities are classified correctly. Keep in sync with
// `apps/core/src/styles/tailwind.css`; the editor keeps a twin copy at
// `packages/editor/src/lib/cn.ts` — the dual copy is guarded by the
// parity test at packages/editor/tests/unit/parity/ui-copies.test.ts.

const TEXT_TOKENS = [
  'admin-sm',
  'admin-base',
  'aplayer-time',
  'badge',
  'btn-lg',
  'empty-state-hero',
  'h-display',
  'h-lg',
  'h-md',
  'h-sm',
  'h-xl',
  'md',
  'micro',
  'nano',
  'toc-link',
  'toc-title',
  'toc-toggle',
  '2xl',
] as const

const COLOR_TOKENS = [
  'accent',
  'accent-foreground',
  'editor-accent',
  'alert',
  'aplayer-bar',
  'aplayer-bar-loaded',
  'aside-bg',
  'background',
  'border',
  'brand',
  'brand-dark',
  'brand-darker',
  'btn-hover-bg',
  'btn-hover-fg',
  'btn-destructive-hover-bg',
  'btn-destructive-hover-fg',
  'btn-light-border',
  'btn-light-bg',
  'btn-light-fg',
  'btn-light-hover-fg',
  'btn-primary-bg',
  'canvas',
  'card',
  'scrim',
  'skeleton-start',
  'skeleton-end',
  'card-foreground',
  'destructive',
  'destructive-foreground',
  'fab-bg',
  'fab-fg',
  'foreground',
  'ga-100',
  'ga-200',
  'ga-300',
  'ga-400',
  'ga-500',
  'ga-600',
  'ink-1',
  'ink-2',
  'ink-3',
  'ink-4',
  'ink-5',
  'ink-on-dark',
  'input',
  'like-active',
  'like-bg',
  'like-bg-hover',
  'line',
  'line-muted',
  'muted',
  'muted-foreground',
  'popover',
  'popover-foreground',
  'popup-close-hover',
  'primary',
  'primary-foreground',
  'ring',
  'secondary',
  'secondary-foreground',
  'sidebar',
  'sidebar-accent',
  'sidebar-accent-foreground',
  'sidebar-border',
  'sidebar-foreground',
  'sidebar-primary',
  'sidebar-primary-foreground',
  'sidebar-ring',
  'surface',
  'surface-body',
  'surface-dim',
  'surface-secondary',
  'surface-soft',
  'surface-warn',
  'warn',
  'widget-border',
  'status-info-bg',
  'status-info-fg',
  'status-info-border',
  'status-warn-bg',
  'status-warn-fg',
  'status-warn-border',
  'status-error-bg',
  'status-error-fg',
  'status-error-border',
  'status-success-bg',
  'status-success-fg',
  'status-success-border',
  'status-draft-bg',
  'status-draft-fg',
  'status-draft-border',
  'diff-change-bg',
  'diff-change-fg',
  'diff-change-border',
  'diff-insert-bg',
  'diff-insert-fg',
  'diff-insert-border',
  'diff-delete-bg',
  'diff-delete-fg',
  'diff-delete-border',
  'chart-1',
  'chart-2',
  'chip-bg',
  'chip-fg',
  'chip-hover-bg',
  'chip-hover-fg',
] as const

const SHADOW_TOKENS = [
  'card',
  'focus',
  'like-active',
  'modal',
  'popup-close',
  'popover',
  'raised',
  'toc-toggle',
  'tooltip',
] as const

const RADIUS_TOKENS = ['aplayer-volume', 'xs', 'sm', 'md', 'lg', 'xl', 'input'] as const

const FONT_TOKENS = ['code'] as const

const ANIMATE_TOKENS = ['comments-shimmer', 'comment-flash'] as const

const Z_INDEX_TOKENS = ['modal', 'aside-drawer'] as const

const SPACING_TOKENS = [
  'admin-col-narrow',
  'admin-thumb',
  'popup-mobile',
  'qr-dialog',
  'aplayer-art-lg',
  'aplayer-art-sm',
  'aplayer-fixed-max',
  'aplayer-icon',
  'aplayer-info-gap-lg',
  'aplayer-lrc',
  'aplayer-lrc-gap',
  'aplayer-info-gap-sm',
  'aplayer-info-pad-top-lg',
  'aplayer-info-pad-x',
  'aplayer-margin',
  'aplayer-miniswitcher-width',
  'aplayer-music-gap',
  'aplayer-music-indent',
  'aplayer-notice-pad-y',
  'aplayer-progress-indent',
  'aplayer-thumb-offset',
  'aplayer-time-height',
  'aplayer-time-pad',
  'aplayer-volume-bar-height',
  'aplayer-volume-bar-indent',
  'aplayer-volume-bar-track',
  'aplayer-volume-indent',
  'aplayer-volume-popup-bottom',
  'aplayer-volume-popup-right',
  'aplayer-volume-popup-width',
  'auth-btn',
  'auth-input',
  'auth-input-pad',
  'badge-overlay-y',
  'btn-icon-md',
  'comment-avatar-gap',
  'editor-min',
  'editor-prose-min',
  'empty-state',
  'header-brand-b',
  'header-brand-x',
  'icon-inset',
  'search-trigger',
  'sidebar-item',
  'submenu-p',
  'submenu-px-lg',
  'toc-disc',
  'toc-disc-hover',
  'toc-disc-open',
  'toc-disc-open-hover',
  'toc-drawer',
  'toc-drawer-edge',
  'toc-toggle-edge-open',
  'admin-content-min',
  'dialog-max-h',
  'dialog-max-h-sm',
  'editor-pad-bottom',
  'content-main',
  'content-side',
  'dialog-popup-md',
] as const

const customTwMerge = extendTailwindMerge({
  extend: {
    theme: {
      text: [...TEXT_TOKENS],
      color: [...COLOR_TOKENS],
      shadow: [...SHADOW_TOKENS],
      radius: [...RADIUS_TOKENS],
      font: [...FONT_TOKENS],
      animate: [...ANIMATE_TOKENS],
      spacing: [...SPACING_TOKENS],
    },
    classGroups: {
      z: ['z-tooltip', 'z-modal', 'z-aside-drawer'],
    },
  },
})

export function cn(...inputs: ClassValue[]): string {
  return customTwMerge(clsx(inputs))
}

export const __TOKENS_FOR_TESTS = {
  registered: {
    text: TEXT_TOKENS,
    color: COLOR_TOKENS,
    shadow: SHADOW_TOKENS,
    radius: RADIUS_TOKENS,
    font: FONT_TOKENS,
    animate: ANIMATE_TOKENS,
    spacing: SPACING_TOKENS,
    'z-index': Z_INDEX_TOKENS,
  } satisfies Record<string, ReadonlyArray<string>>,
  omitted: ['leading'] as const,
} as const
