import type { LexicalEditor, LexicalNode } from 'lexical'

import type { GeneratedDecoratorNodeBase } from '@/ui/inkling-editor/nodes/base/generate-decorator-node'

// Lexical's private fields are not in the public types but are used throughout the codebase
export interface InklingEditorInternals extends LexicalEditor {
  _parentEditor: LexicalEditor | null
  _updating: boolean
}

// Card nodes generated by generateDecoratorNode expose hasEditMode()/getIsVisibilityActive()
// which are not part of Lexical's base LexicalNode type. Cast $getNodeByKey results to this
// when these card-specific methods are needed.
// Additional methods are defined on specific subclasses but used generically across the codebase.
export type CardNode = LexicalNode &
  GeneratedDecoratorNodeBase & {
    isEmpty(): boolean
    __openInEditMode?: boolean
    clearOpenInEditMode?(): void
    selectPrevious?(): void
    selectNext?(): void
  }
