import type { Config as ReactRouterConfig } from '@react-router/dev/config'
import type { IncomingMessage, ServerResponse } from 'node:http'
import type { Plugin, UserConfig } from 'vite'

import honoDevServer, { type DevServerOptions } from '@hono/vite-dev-server'
import nodeAdapter from '@hono/vite-dev-server/node'
import fs from 'node:fs'
import path from 'node:path'

interface ReactRouterHonoServerEnv {
  readonly REACT_ROUTER_HONO_SERVER_BUILD_DIRECTORY: string
  readonly REACT_ROUTER_HONO_SERVER_ASSETS_DIR: string
  readonly REACT_ROUTER_HONO_SERVER_BASENAME: string
}

type MetaEnv<T> = {
  [K in keyof T as `import.meta.env.${string & K}`]: T[K]
}

type ReactRouterHonoServerPluginOptions = {
  /**
   * The path to the server file, relative to `vite.config.ts`.
   *
   * If it is a folder (`app/server`), it will look for an `index.ts` file.
   *
   * Defaults to `${appDirectory}/server[.ts | /index.ts]` if present.
   *
   * Fallback to a virtual module `virtual:react-router-hono-server/server`.`
   */
  serverEntryPoint?: string
  /**
   * The paths that are not served by the dev-server.
   *
   * Defaults include `appDirectory` content.
   */
  dev?: {
    /**
     * The paths that are not served by the dev-server.
     *
     * Defaults include `appDirectory` content.
     */
    exclude?: DevServerOptions['exclude']
    /**
     * The name of the export to use for the server.
     *
     * Defaults to `default`.
     */
    export?: DevServerOptions['export']
  }
}

const REACT_ROUTER_SERVER_BUILD_MODULE_ID = '\0virtual:react-router/server-build'
const VIRTUAL_MODULE_ID = '\0virtual:react-router-hono-server/server'

export function reactRouterHonoServer(options: ReactRouterHonoServerPluginOptions = {}): Plugin {
  let pluginConfig: PluginConfig
  let devServerPlugin: Plugin | undefined

  return {
    name: 'react-router-hono-server',
    enforce: 'post',
    resolveId(id) {
      if (id === VIRTUAL_MODULE_ID) {
        return id
      }
    },
    load(id) {
      if (id === VIRTUAL_MODULE_ID) {
        return `
          // generated by react-router-hono-server/dev
          import { createHonoServer } from "@/server/infra/hono/node";

          export default await createHonoServer();
        `
      }
    },
    async config(config, _env) {
      pluginConfig = resolvePluginConfig(config, options)

      if (!pluginConfig) {
        return
      }

      const isEnvironmentApiEnabled = (pluginConfig.future as { v8_viteEnvironmentApi?: boolean }).v8_viteEnvironmentApi

      const serverEntryPoint = pluginConfig.serverEntryPoint

      const baseConfig = {
        define: {
          'import.meta.env.REACT_ROUTER_HONO_SERVER_BUILD_DIRECTORY': JSON.stringify(pluginConfig.buildDirectory),
          'import.meta.env.REACT_ROUTER_HONO_SERVER_ASSETS_DIR': JSON.stringify(pluginConfig.assetsDir),
          'import.meta.env.REACT_ROUTER_HONO_SERVER_BASENAME': JSON.stringify(pluginConfig.basename),
        } satisfies MetaEnv<ReactRouterHonoServerEnv>,
        ssr: {
          noExternal: [],
        },
      } satisfies UserConfig

      if (!isEnvironmentApiEnabled && !pluginConfig.isSsrBuild) {
        return baseConfig
      }

      let reactRouterBuildFile = pluginConfig.serverBuildFile

      if (reactRouterBuildFile === 'index.js') {
        reactRouterBuildFile = 'assets/server-build.js'
      }

      const ssrConfig = {
        build: {
          rollupOptions: {
            input: serverEntryPoint,
            output: {
              entryFileNames: (chunk: any) => {
                chunk.facadeModuleId = REACT_ROUTER_SERVER_BUILD_MODULE_ID
                return 'index.js'
              },
              chunkFileNames: (chunk: any) => {
                if (chunk.name === 'server-build') {
                  return reactRouterBuildFile
                }
                return 'assets/[name]-[hash].js'
              },
              manualChunks: (id: string, meta: any) => {
                if (meta.getModuleInfo(id)?.importers.some((id: string) => id.includes(serverEntryPoint))) {
                  return path.basename(id, path.extname(id))
                }
                return undefined
              },
            },
          },
        },
      } satisfies Omit<UserConfig, 'plugins'>

      if (isEnvironmentApiEnabled) {
        return {
          ...baseConfig,
          environments: {
            ssr: ssrConfig as any,
          },
        }
      }

      return {
        ...baseConfig,
        ...ssrConfig,
      }
    },
    async configureServer(server) {
      globalThis.__viteDevServer = server

      if (!pluginConfig) {
        return
      }

      if (devServerPlugin) {
        return
      }

      devServerPlugin = honoDevServer({
        adapter: nodeAdapter,
        injectClientScript: false,
        entry: pluginConfig.serverEntryPoint,
        export: options.dev?.export || 'default',
        exclude: [
          new RegExp(
            `^(?=\\/${pluginConfig.appDirectory.replace(/^[/\\]+|[/\\]+$/g, '').replaceAll(/[/\\]+/g, '/')}\\/)((?!.*\\.data(\\?|$)).*\\..*(\\?.*)?$)`,
          ),
          new RegExp(
            `^(?=\\/${
              pluginConfig.appDirectory
                .replace(/^[/\\]+|[/\\]+$/g, '')
                .replaceAll(/[/\\]+/g, '/')
                .split('/')[0]
            }\\/)((?!.*\\.data(\\?|$)).*\\..*(\\?.*)?$)`,
          ),
          /\?import(\?.*)?$/,
          /^\/@.+$/,
          /^\/node_modules\/.*/,
          `^(?=\\/${pluginConfig.appDirectory.replace(/^[/\\]+|[/\\]+$/g, '').replace(/[/\\]+/g, '/')}/**/.*/**)`,
          `^(?=\\/${
            pluginConfig.appDirectory
              .replace(/^[/\\]+|[/\\]+$/g, '')
              .replace(/[/\\]+/g, '/')
              .split('/')[0]
          }/**/.*/**)`,
          ...(pluginConfig.dev?.exclude || []),
        ],
      })

      server.middlewares.use((req: IncomingMessage, _res: ServerResponse, next: () => void) => {
        req.rawHeaders.push('x-remote-address', req.socket.remoteAddress || 'unknown')
        req.rawHeaders.push('x-remote-port', String(req.socket.remotePort || 'unknown'))
        req.rawHeaders.push('x-remote-family', req.socket.remoteFamily || 'unknown')
        next()
      })

      if (typeof devServerPlugin.configureServer === 'function') {
        await (devServerPlugin.configureServer as any)(server)
      } else {
        // oxlint-disable-next-line no-console
        console.error('Dev server plugin configureServer hook is not a function. This is likely a bug, I guess 😅\n')
        throw new Error('Cannot apply dev server plugin configureServer hook')
      }
    },
  }
}

type ReactRouterPluginContext = {
  reactRouterConfig: Required<ReactRouterConfig>
  environmentBuildContext: { name: 'client' | 'ssr' } | null
  rootDirectory: string
  entryClientFilePath: string
  entryServerFilePath: string
}

function resolvePluginConfig(config: UserConfig, options: ReactRouterHonoServerPluginOptions) {
  if (!('__reactRouterPluginContext' in config)) {
    return null
  }

  const { reactRouterConfig, environmentBuildContext, rootDirectory } =
    config.__reactRouterPluginContext as ReactRouterPluginContext
  const buildDirectory = path.relative(rootDirectory, reactRouterConfig.buildDirectory)
  const appDirectory = path.relative(rootDirectory, reactRouterConfig.appDirectory)
  const isSsrBuild = environmentBuildContext?.name === 'ssr'
  const assetsDir = config.build?.assetsDir || 'assets'
  const serverEntryPoint = options.serverEntryPoint || findDefaultServerEntry(appDirectory)
  const serverBuildFile = reactRouterConfig.serverBuildFile
  const basename = reactRouterConfig.basename
  const future = reactRouterConfig.future

  return {
    rootDirectory,
    buildDirectory,
    appDirectory,
    isSsrBuild,
    assetsDir,
    serverEntryPoint,
    dev: options.dev,
    serverBuildFile,
    basename,
    future,
  }
}

type PluginConfig = ReturnType<typeof resolvePluginConfig>

let warned = false

function findDefaultServerEntry(appDirectory: string): string {
  const fileWay = `${appDirectory}/server.ts`
  const folderWay = `${appDirectory}/server/index.ts`

  if (fs.existsSync(fileWay)) {
    return fileWay
  }

  if (fs.existsSync(folderWay)) {
    return folderWay
  }

  if (!warned) {
    // oxlint-disable-next-line no-console
    console.warn(
      `No server entry point found. Will use a virtual module (${VIRTUAL_MODULE_ID}) with a default Hono server.`,
    )
    warned = true
  }
  return VIRTUAL_MODULE_ID
}
