import { createMiddleware } from 'hono/factory'

/**
 * Streaming GET/HEAD proxy for the frontend's URL-endpoint surface
 * (headless phase 2).
 *
 * Under the two-service topology the public site's canonical domain is
 * served by the frontend, but the URL-shaped resources (feeds, sitemap,
 * robots, brand assets, OG/calendar/avatar images, /storage media,
 * embedded fonts) are generated by core — core owns the database and the
 * render pipeline. This middleware forwards those GET/HEAD requests to
 * `coreApiUrl + pathname + search` and relays the upstream response
 * WITHOUT buffering (`new Response(upstream.body, …)`): large media
 * streams byte-for-byte, range requests keep their seek semantics, and
 * a slow feed generator does not balloon frontend memory.
 *
 * Request-headers are a strict allowlist — the frontend owns nothing
 * else, and crucially `cookie` / `Authorization` are never forwarded
 * (the visitor's frontend-domain cookies mean nothing to core, and a
 * forwarded browser Authorization header would be a credential leak).
 *
 * Response relay is verbatim: status, headers (ETag, Cache-Control,
 * Content-Type, Content-Range, Accept-Ranges, Last-Modified, …), and
 * body stream. `redirect: 'manual'` keeps core's 301/302 (e.g. the
 * OG fallback redirect to `/images/open-graph.png`) intact for the
 * browser to follow, 304s pass through when the visitor sent
 * `if-none-match`, and 206s flow when `range` was forwarded.
 *
 * Failure semantics: an unreachable core answers 503 with a short text
 * body (never swallowed into a 200).
 */

/** Browser request headers forwarded verbatim to core. */
const FORWARD_HEADERS = ['accept', 'accept-encoding', 'if-none-match', 'range', 'user-agent'] as const

/** Response headers the upstream may set; relayed verbatim by construction. */
// (No allowlist here — every upstream header is copied as-is.)

export interface GetProxyOptions {
  /** Core base URL (`CORE_API_URL`) — the URL endpoint mount is appended. */
  coreApiUrl: string | null
}

/**
 * Build the middleware that proxies one URL-endpoint path pattern.
 * Mount with `app.use(pattern, createGetProxy(...))` — any method other
 * than GET/HEAD falls through (`next()`), so the local redirect routes
 * and the React Router handler below still see them.
 */
export function createGetProxy(options: GetProxyOptions) {
  const trimmed = options.coreApiUrl?.trim()
  const coreBase = trimmed !== undefined && trimmed !== '' ? trimmed.replace(/\/+$/, '') : null

  return createMiddleware(async (c, next) => {
    if (c.req.method !== 'GET' && c.req.method !== 'HEAD') {
      return next()
    }
    if (coreBase === null) {
      // No configured core: the endpoint cannot be served. The /health
      // probe already surfaces the misconfiguration; answer resource
      // requests with a short 503 instead of a misleading 404.
      return c.text('Core is not configured — the URL endpoint cannot be served', 503)
    }

    const headers = new Headers()
    for (const name of FORWARD_HEADERS) {
      const value = c.req.header(name)
      if (value !== undefined) {
        headers.set(name, value)
      }
    }

    const rawUrl = new URL(c.req.raw.url)
    const target = `${coreBase}${rawUrl.pathname}${rawUrl.search}`

    let upstream: Response
    try {
      upstream = await fetch(target, { method: c.req.method, headers, redirect: 'manual' })
    } catch {
      return c.text('Core is unreachable — the URL endpoint could not be served', 503)
    }

    return new Response(upstream.body, { status: upstream.status, headers: upstream.headers })
  })
}
