import { Hono } from 'hono'

import { createEndpointCache } from '@/lib/http/endpoint-cache'
import { createGetProxy } from '@/lib/http/get-proxy'
import { createWebmentionProxy, type WebmentionProxyOptions } from '@/lib/http/webmention-proxy'

/**
 * URL-endpoint proxy mount table (headless phase 2).
 *
 * The public site's canonical domain is served by the frontend, but the
 * URL-shaped resources below are generated by core. This table is the
 * SINGLE list of what the frontend forwards; the contract test
 * (`apps/public/tests/unit/lib/http/proxy-routes.test.ts`) pins it
 * 1:1 against core's actual resource mounts so neither side can drift.
 *
 * Patterns are deliberately WIDE (`/storage/*`, `/images/og/*`): the
 * proxy only decides WHETHER to forward — parameter parsing happens in
 * core, which receives the original pathname untouched. A wide pattern
 * therefore never changes core's routing semantics (e.g.
 * `/images/calendar/dark/:year/*` also matches the non-dark pattern
 * below, but core re-routes the forwarded path itself).
 *
 * NOT in the table (by design):
 *   - `/assets/*` — the frontend serves its own fingerprinted client
 *     assets locally (disk / SEA embedded);
 *   - `/tags`, `/search` — local 301 replicates of core's legacy
 *     redirects (registered below, never proxied);
 *   - `/webmention` — POST proxy (below), not a GET forward.
 */
export const URL_PROXY_ROUTES: readonly string[] = [
  // Syndication feeds (6): site-wide + category + tag, RSS + Atom.
  '/feed',
  '/feed/atom',
  '/cats/:slug/feed',
  '/cats/:slug/feed/atom',
  '/tags/:slug/feed',
  '/tags/:slug/feed/atom',
  // SEO / PWA entry points.
  '/sitemap.xml',
  '/robots.txt',
  '/manifest.webmanifest',
  // Brand assets (14) — matches `ASSET_ROUTES` in the server package's
  // `domains/assets/services/routes.ts` 1:1. `?original` and the
  // ETag/304 conditional flow pass through via the verbatim relay.
  '/favicon.svg',
  '/logo.svg',
  '/logo-dark.svg',
  '/logo-large.svg',
  '/logo-large-dark.svg',
  '/favicon.ico',
  '/apple-touch-icon.png',
  '/images/icon-192.png',
  '/images/icon-512.png',
  '/images/open-graph.png',
  '/images/blog-poster.png',
  '/images/blog-poster-dark.png',
  '/images/default-avatar.png',
  '/images/default-music-cover.png',
  // Generated images: OG cards, calendars, comment avatars (`?s=` size).
  '/images/og/*',
  '/images/og/cats/*',
  '/images/calendar/:year/*',
  '/images/calendar/dark/:year/*',
  '/images/avatar/*',
  // Local-storage media (range requests for audio seek pass through).
  '/storage/*',
  // Self-hosted web-font packages.
  '/fonts/embedded/*',
] as const

/** `?original` and `?s=` are the only query params core reads on the
 *  proxied surface; the relay passes the full query string untouched. */

const LEGACY_REDIRECT_CACHE_CONTROL = 'public, max-age=86400, s-maxage=604800, immutable'

// Process-local short TTLs for the two proxied families core already
// marks cacheable — aligned with core's actual Cache-Control values
// (`packages/server/src/http/resources/feed.ts` → `max-age=1800`,
// `sitemap.ts` → `max-age=3600`), so the frontend cache never outlives
// what core itself promised. Everything else in the mount table stays
// uncached (media streams, redirects, 304/206 conditional flows).
const FEED_CACHE_TTL_MS = 1800 * 1000
const SITEMAP_CACHE_TTL_MS = 3600 * 1000

/** The 6 feed patterns of the mount table (site-wide + category + tag, RSS + Atom). */
export const FEED_PATTERNS = URL_PROXY_ROUTES.filter(
  (pattern) => pattern.endsWith('/feed') || pattern.endsWith('/feed/atom'),
)

export interface UrlProxyAppOptions extends WebmentionProxyOptions {
  /** Core base URL (`CORE_API_URL`). */
  coreApiUrl: string | null
}

/**
 * Assemble the frontend's URL-endpoint face: local 301 replicates
 * first (they must win over the wide GET proxy), then the streaming GET
 * proxy for every table entry, then the `/webmention` POST proxy.
 *
 * Registration order mirrors core (`middleware-pipeline.ts`): redirects
 * and resource routes are Hono siblings, and `/webmention` answers only
 * POST while the GET surface falls through to the router.
 */
export function createUrlProxyApp(options: UrlProxyAppOptions): Hono {
  const app = new Hono()

  // Legacy navigation entry points — local 301 replicates of core's
  // `redirectsRouter`, served WITHOUT a core round-trip (a redirect is
  // cheaper than a proxied one and works even while core is down).
  app.get('/tags', (c) => {
    c.header('Cache-Control', LEGACY_REDIRECT_CACHE_CONTROL)
    return c.redirect('/', 301)
  })
  app.get('/search', (c) => {
    const query = c.req.query('q')?.trim() ?? ''
    c.header('Cache-Control', LEGACY_REDIRECT_CACHE_CONTROL)
    return c.redirect(query ? `/search/${encodeURIComponent(query)}` : '/', 301)
  })

  const getProxy = createGetProxy({ coreApiUrl: options.coreApiUrl })
  // Feeds + sitemap ride a process-local short TTL cache in front of the
  // relay (see `endpoint-cache.ts` for the semantics); the remaining
  // table entries proxy verbatim, uncached.
  for (const pattern of FEED_PATTERNS) {
    app.use(pattern, createEndpointCache({ ttlMs: FEED_CACHE_TTL_MS }), getProxy)
  }
  app.use('/sitemap.xml', createEndpointCache({ ttlMs: SITEMAP_CACHE_TTL_MS }), getProxy)
  for (const pattern of URL_PROXY_ROUTES) {
    if (pattern === '/sitemap.xml' || FEED_PATTERNS.includes(pattern)) {
      continue
    }
    app.use(pattern, getProxy)
  }

  app.post('/webmention', createWebmentionProxy(options))

  return app
}
