import type { LexicalNode } from 'lexical'

import type { CardSpecFieldMap } from '@/nodes/base/card-specs'
import type { GeneratedDecoratorNodeBase } from '@/nodes/base/generate-decorator-node'
import type { codeBlockDeclaration } from '@/nodes/cards/codeblock.declaration'

// Card nodes generated by generateDecoratorNode expose hasEditMode()
// which is not part of Lexical's base LexicalNode type. Cast $getNodeByKey results to this
// when these card-specific methods are needed.
// Additional methods are defined on specific subclasses but used generically across the codebase.
export type CardNode = LexicalNode &
  GeneratedDecoratorNodeBase & {
    // only some card classes implement isEmpty; cards without it are never auto-removed
    isEmpty?(): boolean
    // the open-in-edit-mode transient facts are spec-derived — a rename of the
    // codeblock declaration's privateName/initial is a compile error here, so
    // the fixture cannot drift from the spec vocabulary (clearOpenInEditMode
    // is a hand-written method on CodeBlockNode, not spec data)
    __openInEditMode?: CardSpecFieldMap<typeof codeBlockDeclaration>['__openInEditMode']
    clearOpenInEditMode?(): void
  }
