import DOMPurify from 'dompurify'

export type SafeHtmlStrategy = 'shiki' | 'math' | 'email' | 'audit' | 'preview'

export function sanitizeHtml(html: string, strategy: SafeHtmlStrategy): string {
  return DOMPurify.sanitize(html, strategyToConfig(strategy)) as string
}

function strategyToConfig(strategy: SafeHtmlStrategy): NonNullable<Parameters<typeof DOMPurify.sanitize>[1]> {
  const base: NonNullable<Parameters<typeof DOMPurify.sanitize>[1]> = {
    ALLOWED_TAGS: [
      'div',
      'span',
      'p',
      'br',
      'hr',
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      'ul',
      'ol',
      'li',
      'strong',
      'b',
      'em',
      'i',
      'code',
      'pre',
      'a',
      'img',
      'table',
      'thead',
      'tbody',
      'tr',
      'td',
      'th',
    ],
    ALLOWED_ATTR: ['class', 'href', 'title', 'alt', 'target', 'rel', 'data-*'],
    ALLOW_DATA_ATTR: true,
  }

  switch (strategy) {
    case 'shiki':
      return {
        ...base,
        ALLOWED_TAGS: [...(base.ALLOWED_TAGS ?? []), 'span', 'code', 'pre', 'div', 'line'],
        ALLOWED_ATTR: [
          ...(base.ALLOWED_ATTR ?? []),
          'class',
          'style',
          'data-language',
          'data-rehype-pretty-code-fragment',
          'data-rehype-pretty-code-title',
        ],
      }

    case 'math':
      return {
        ...base,
        ALLOWED_TAGS: [
          ...(base.ALLOWED_TAGS ?? []),
          'math',
          'mrow',
          'mi',
          'mo',
          'mn',
          'msup',
          'msub',
          'msubsup',
          'mfrac',
          'msqrt',
          'mroot',
          'mtext',
          'munder',
          'mover',
          'munderover',
          'mfenced',
          'mstyle',
          'mspace',
          'mpadded',
          'menclose',
          'semantics',
          'annotation',
          'annotation-xml',
          'svg',
          'g',
          'path',
          'rect',
          'circle',
          'ellipse',
          'line',
          'polyline',
          'polygon',
          'text',
          'tspan',
          'defs',
          'use',
          'clipPath',
          'foreignObject',
        ],
        ALLOWED_ATTR: [
          ...(base.ALLOWED_ATTR ?? []),
          'xmlns',
          'display',
          'overflow',
          'mathcolor',
          'mathbackground',
          'mathsize',
          'mathvariant',
          'fence',
          'stretchy',
          'lspace',
          'rspace',
          'maxsize',
          'minsize',
          'movablelimits',
          'accent',
          'accentunder',
          'symmetric',
          'largeop',
          'displaystyle',
          'scriptlevel',
          'columnalign',
          'columnspacing',
          'rowspacing',
          'rowalign',
          'frame',
          'framespacing',
          'width',
          'height',
          'depth',
          'linethickness',
          'bevelled',
          'open',
          'close',
          'separators',
          'notation',
          'subscriptshift',
          'superscriptshift',
          'x',
          'y',
          'x1',
          'y1',
          'x2',
          'y2',
          'cx',
          'cy',
          'r',
          'rx',
          'ry',
          'points',
          'd',
          'fill',
          'stroke',
          'stroke-width',
          'transform',
          'viewBox',
          'preserveAspectRatio',
          'marker',
          'marker-start',
          'marker-end',
          'marker-mid',
          'clip-path',
          'mask',
          'id',
          'href',
          'xlink:href',
        ],
      }

    case 'email':
      return {
        ...base,
        ALLOWED_ATTR: [
          ...(base.ALLOWED_ATTR ?? []),
          'bgcolor',
          'color',
          'align',
          'valign',
          'border',
          'cellpadding',
          'cellspacing',
          'colspan',
          'rowspan',
          'width',
          'height',
          'src',
        ],
      }

    case 'audit':
    case 'preview':
    default:
      return base
  }
}
